Feature/endpoint login usuario
J-edu-lima/ToDoList---Java-project pull request #4
Opened 2024-09-17 23:44 UTC by J-edu-lima

2024-09-18 00:28 UTC, enzofalvo requested changes
Unica classe que eu gostaria de revisar e faltou pq acho que ela não apareceu no PR, é a UserDetails, se puder depois só me mostrar o que ela faz / para que serve

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/auth/controllers/AuthController.java
> +    @PostMapping("/register")
Colocar o nome do endpoint em PTBR

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +
```suggestion
@Service
public class AuthorizationService implements UserDetailsService{
   
     @Autowired
    private ApplicationContext context;
    
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +    }
Nome das variaveis em PTBR

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +    private AuthenticationManager authenticationManager;
Nome da classe em PTBR

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +
Retirar espaços em branco

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +    }
Arrumar formatação

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +    public ResponseEntity<Object> register (@RequestBody RegisterDto registerDto){
Nome do método em PTBR

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
> +	@PostMapping("/criar/{id}")
Não precisa desse **criar**, quem vai dizer se é um GET, DELETE, PUT, PATCH ETC é o próprio verbo que a pessoa vai colocar no postman / requisição HTTP. Não precisa disso, não é uma boa prática.

Já existe o `@Postmapping` que vc está usando afirmando que é um POST

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
> +	@PostMapping("/criar/{id}")
```suggestion
	@PostMapping("/{id}")
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
> +	@DeleteMapping("/deletar/{id}")
```suggestion
	@DeleteMapping("/{id}")
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
> +	public ResponseEntity<Void> exlcuir(@PathVariable("id") Long id) {
```suggestion
	public ResponseEntity<Void> excluir(@PathVariable("id") Long id) {
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
> +	@GetMapping("/status/{status}")
```suggestion
	@GetMapping("/{id}")
```

é passado um id, certo? ou é passado um status?

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
> +	@PutMapping("/atualizar/{id}")
```suggestion
	@PutMapping("/{id}")
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
> +	}
```suggestion
		TarefaEntity tarefa = tarefaService.buscar(id);
		tarefaService.atualizar(novoStatus, tarefa);
		
		return ResponseEntity.noContent().build();
	}
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/UsuarioController.java
Nessa classe pode corrigir os mesmos apontamentos que deixei na TarefaController.java

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/controller/UsuarioController.java
> +		List<CriarUsuarioEntradaDTO> listDto = list.stream().map(x -> new CriarUsuarioEntradaDTO(x))
O que é uma listDto? uma lista de DTO's, certo?

Mas uma lista de DTO's do que? pode ser de vários tipos diferentes, aqui não está especificado que é de clientes

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/dtos/AuthenticationDto.java
Essa classe está vazia?

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/dtos/LoginResponseDto.java
Essa classe está vazia?

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/dtos/RegisterDto.java
Faz sentido termos essa classe?

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/TarefaEntity.java
> +@DynamicUpdate(true)
Pra que serve esse DynamicUpdate?

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +public class UsuarioEntity implements UserDetails {
Por que a Entity está implementando o UserDetails?

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +	@SuppressWarnings("static-access")
Por que dessa linha?

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +		else return List.of(new SimpleGrantedAuthority("ROLE_USER"));
Usar chaveamento para não fazer if else na mesma linha, o que acaba prejudicando a legibilidade.

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +	}
Usar anotação `@Getter` e `@Setter` no começo da classe para não precisar desses getter's e setter's

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/enums/Status.java
> +	CRIADA("CRIADA"), INICIADA("INICIADA"), CONCLUIDA("CONCLUIDA");
Se eu não me engano, não precisa replicar o mesmo nome para o valor de cada tipo enumerado. Pode manter como estava antes que ele funciona, se não me engano.

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/enums/Status.java
> +	CRIADA("CRIADA"), INICIADA("INICIADA"), CONCLUIDA("CONCLUIDA");
CRIADA, INICIADA, CONCLUIDA;

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/enums/Status.java
> +	CRIADA("CRIADA"), INICIADA("INICIADA"), CONCLUIDA("CONCLUIDA");
Só pular uma linha entre elas:
```suggestion
	CRIADA, 
	INICIADA, 
	CONCLUIDA;
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/entity/enums/Status.java
> +	}
Usar `@Getter` e `@Setter`

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/service/impl/UsuarioServiceImpl.java
> +
```suggestion
```

2024-09-18 00:28 UTC, enzofalvo commented on src/main/java/com/joseeduardo/todoist/service/impl/UsuarioServiceImpl.java
> +@RequiredArgsConstructor
Pra que essa linha?

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/auth/controllers/AuthController.java
> +    public ResponseEntity<Object> login(@RequestBody @Valid AuthenticationDto authetinticationDto){
@enzofalvo o requestBody não deveria ser uma classe tipo authetinticationRequest?

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/auth/controllers/AuthController.java
> +        return authorizationService.login(authetinticationDto);
ai quando for passar para a service utilizar um mapper para converter para dto

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/auth/controllers/AuthController.java
> +    public ResponseEntity<Object> register (@RequestBody RegisterDto registerDto){
ditto

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +    public ResponseEntity<Object> login(@RequestBody @Valid AuthenticationDto data){
@enzofalvo, precisa da annotation @RequestBody na service?

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +        var usernamePassword = new UsernamePasswordAuthenticationToken(data.nome(), data.senha());
Classe AuthenticationDto esta sem campos nem validações, pode cair em uma exception caso nome ou senha esteja vazio

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/auth/service/AuthorizationService.java
> +    public ResponseEntity<Object> register (@RequestBody RegisterDto registerDto){
ditto @RequestBody

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/config/TestConfig.java
> +package com.joseeduardo.todoist.config;
o nome do package errado "todoist"

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
>  package com.joseeduardo.todoist.controller;
ditto "todoist"

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
>  	public ResponseEntity<Void> criar(@RequestBody CriarTarefaEntradaDTO criarTarefaEntradaDTO,
ditto criarTarefaEntradRequest

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/controller/TarefaController.java
>  	public ResponseEntity<Void> criar(@RequestBody CriarTarefaEntradaDTO criarTarefaEntradaDTO,
```suggestion
	public ResponseEntity<Void> criar(@RequestBody CriarTarefaEntradaDTO criarTarefaEntradaRequest,
```

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
>  	public String getNome() {
@enzofalvo Não é mais facil usar as annotation @Getter @Setter?

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +	public String getPassword() {
ditto annotation @Getter

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +	public String getUsername() {
ditto

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +	public UserRole getUserRole() {
ditto

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +	}
ih ala, foi oq eu falei, grande @enzofalvo muito brabo

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/entity/UsuarioEntity.java
> +public class UsuarioEntity implements UserDetails {
```suggestion
@Getter
@Setter
public class UsuarioEntity implements UserDetails {
```

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/model/CriarTarefaEntradaDTO.java
> +	public CriarTarefaEntradaDTO(Long id, String titulo, String descrição, Status status) {
usa o `@AllArgsConstructor ` ai não precisa construir um na mão

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/model/CriarTarefaEntradaDTO.java
>  public class CriarTarefaEntradaDTO {
```suggestion
@Getter
@Setter
@AllArgsConstructor 
public class CriarTarefaEntradaDTO {
```

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/model/CriarUsuarioEntradaDTO.java
> +	public CriarUsuarioEntradaDTO(String nome, String senha, UserRole role) {
ditto

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/security/TokenService.java
> +			throw new RuntimeException("ERRO NA HORA DE GERAR O TOKEN", exception);
Acho que a mensagem pode ser "Erro ao gerar token", mas é so eu sendo chato

2024-09-20 23:31 UTC, Andrey-Meira commented on src/main/java/com/joseeduardo/todoist/security/enums/UserRole.java
> +public enum UserRole {
ditto getter setter

2024-09-26 02:52 UTC, closed without merging